name: botender
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - pip

  # code-checks
  - pre-commit>=2.15

  # frameworks
  - pytorch::pytorch>=2.1
  - pytorch::torchvision>=0.16
  - opencv>=4.8

  - pip:
      # code-checks
      - ruff>=0.1

      # tools
      - jupyter>=1.0
      - ipympl>=0.9
      - pandas-stubs>=2.1
      - furhat_remote_api>=1.0
      - imageio[ffmpeg]>=2.33
      - numpy>=1.26
      - opencv_jupyter_ui>=1.4
      - py-feat>=0.6
      - skorch>=0.15
      - colorlog>=6.7
